force-app/main/default/objects/Star_Wars_character__c/Star_Wars_character__c.object-meta.xml
<CustomObject>
    <label>Star Wars character</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_character__c/fields/Birth_year__c.field-meta.xml
<CustomField>
    <fullName>Birth_year__c</fullName>
    <label>Birth year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_character__c/fields/Films__c.field-meta.xml
<CustomField>
    <fullName>Films__c</fullName>
    <label>Films</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_character__c/fields/Hair_color__c.field-meta.xml
<CustomField>
    <fullName>Hair_color__c</fullName>
    <label>Hair color</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_character__c/fields/Homeworld__c.field-meta.xml
<CustomField>
    <fullName>Homeworld__c</fullName>
    <label>Homeworld</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Star_Wars_character__c/fields/Skin_color__c.field-meta.xml
<CustomField>
    <fullName>Skin_color__c</fullName>
    <label>Skin color</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StarWarsController.cls
public with sharing class StarWarsController {
   
    @AuraEnabled
    public static StarWarsApiResponse setSwId(Integer swId){
        StarWarsApiResponse swRes = new StarWarsApiResponse();
        if(swId != null){
          HttpResponse response =  makeGetCallout(swId);
            // If the request is successful, parse the JSON response.
            if (response.getStatusCode() == 200) {
            // Deserializes the JSON string into StarWarsApiResponse of reference data types.
                swRes = (StarWarsApiResponse) JSON.deserialize(response.getBody(), StarWarsApiResponse.class);
            }
        }
        return swRes;
    }
    @AuraEnabled
    public static Star_Wars_character__c saveRecord(StarWarsApiResponse swRes){
        try {
       Star_Wars_character__c swChar = new Star_Wars_character__c();
       swChar.Name = swRes.name;
       swchar.Height__c = swRes.height;
       swChar.Hair_color__c = swRes.hair_color;
       swChar.Homeworld__c = swRes.homeworld;
       swchar.Skin_color__c = swRes.skin_color;
       swChar.Films__c = swRes.films[0];
       swChar.Birth_year__c = swRes.birth_year;
       
       insert swChar;
            
       return swChar;    
        } catch (DmlException e) {
            System.debug(e.getMessage());
           return null;
        }
    }
    public static HttpResponse makeGetCallout(Integer swId){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept','application/json');
        request.setEndpoint('https://swapi.dev/api/people/'+swId);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        while (response.getStatusCode() == 301 || response.getStatusCode() == 302)
        {
            request.setEndpoint(response.getHeader('Location'));
            response = new Http().send(request);
        }
      

        return response;

    }
  




}